# language                  If the language specified does not exist, a new language file will be added to the
#                           lang folder in the FastCraftPlus plugin directory.
#                           Available languages:
#                           English (EN), Deutsch (DE), Русский язык (RU), Čeština (CS),
#                           Türkçe (TR), Nederlands (NL), 简体中文 (CN)
#
# default-enabled           Whether FastCraft+ is enabled for players by default.
#
# toolbar.gap               Whether there should be a gap between the toolbar and the craftable items.
# toolbar.layout            The locations of buttons in the toolbar. Set a button to -1 to disable it.
# toolbar.multiplier-order  The multipliers used when clicking on the multiplier button.

language: EN

default-enabled: true

toolbar:
  gap: true
  layout:
    page-prev: 0
    page-next: 8
    multiplier: 3
    workbench: 4
    refresh: 5
  multiplier-order: 1, 2, 3, 4, 6, 8, 12, 16, 24, 32, 48, 64
