# language          If the language specified does not exist, a new language file will be added to the
#                   lang folder in the FastCraftPlus plugin directory.
#                   Available languages:
#                   English (EN), Deutsch (DE), Русский язык (RU), Čeština (CS), Türkçe (TR), Nederlands (NL)
#
# default-enabled   Whether FastCraft+ is enabled for players by default.

language: EN

default-enabled: true
