name: FastCraftPlus
author: Kepler_
version: ${project.version}

description: Improved crafting in Minecraft.

main: co.kepler.fastcraftplus.FastCraft

softdepend:
- ItemMakerPro
- ProRecipes

commands:
#  fastcraft:
#    description: FastCraft+ commands
#    usage: /<command>
#    aliases: [fc]

  fastcraftadmin:
    description: FastCraft+ admin commands
    usage: /<command>
    aliases: [fcadmin, fca]

#  craft:
#    description: Open a crafting inventory
#    usage: /<command>
#    aliases: [cr, workbench, wb]

permissions:
  fastcraft.*:
    description: All FastCraft+ permissions
    default: op
    children:
      fastcraft.use: true
      fastcraft.craft: true
      fastcraft.admin.*: true

  fastcraft.use:
    description: Permission to use FastCraft+ for crafting
    default: true

  fastcraft.toggle:
    description: Permission for a player to enable/disable FastCraft+
    default: true
    children:
      fastcraft.toggle.other: false

  fastcraft.toggle.other:
    description: Permission to toggle FastCraft+ for another player
    default: op

  fastcraft.craft:
    description: Permission to use /fastcraft craft
    default: false

  fastcraft.admin.*:
    description: All FastCraft+ admin permissions
    default: op
    children:
      fastcraft.admin.reload: true

  fastcraft.admin.reload:
    description: Reload FastCraft+ config files
    default: op
