name: ${plugin_name}
author: ${plugin_author}
version: ${plugin_version}

description: ${plugin_description}

main: co.kepler.fastcraft.FastCraft

softdepend:
- ItemMakerPro
- ProRecipes

commands:
  fastcraft:
    description: FastCraft commands
    usage: /<command>
    aliases: [fc]

  fastcraftadmin:
    description: FastCraft admin commands
    usage: /<command>
    aliases: [fcadmin, fca]

  craft:
    description: Open a crafting inventory
    usage: /<command>
    aliases: [workbench]

permissions:
  fastcraft.use:
    description: Permission to use FastCraft for crafting
    default: op

  fastcraft.command.*:
    description: All non-admin FastCraft commands
    default: op
    children:
      fastcraft.craft: true
      fastcraft.toggle: true
      fastcraft.toggle.other: true

  fastcraft.command.toggle:
    description: Permission for a player to enable/disable FastCraft
    default: op
    children:
      fastcraft.toggle.other: false
      fastcraft.toggle: true #FastCraft backwards compatibility

  fastcraft.command.toggle.other:
    description: Permission to toggle FastCraft for another player
    default: op
    children:
      fastcraft.toggle.other: true #FastCraft backwards compatibility

  fastcraft.command.craft:
    description: Permission to use /fastcraft craft
    default: op

  fastcraft.admin.*:
    description: All FastCraft admin permissions
    default: op
    children:
      fastcraft.admin.reload: true

  fastcraft.admin.reload:
    description: Reload FastCraft config files
    default: op

  fastcraft.admin.update:
    description: Download FastCraft updates
    default: op

  fastcraft.blacklist.*:
    description: Exemption from all blacklist items
    default: false
