name: FastCraftPlus
author: Kepler_
version: ${project.version}

description: Improved crafting in Minecraft.

main: co.kepler.fastcraftplus.FastCraft

commands:
  fastcraft:
    description: FastCraft commands.
    usage: /fastcraft
    aliases:
      -fc
